### ISSUE TITLE
Aesthetics and spellings

### ISSUE THREAD

**Issue by share-hub** [Pujan789556/BrickKiln#14]
I believe these are not final yet. Yet included a couple of screenshots, just in case (for typos)
![screenshot_2015-01-22-13-33-40 1](https://cloud.githubusercontent.com/assets/5178597/5852333/351b31b8-a23d-11e4-96c8-a502d3c858e8.png)

![screenshot_2015-01-22-13-48-48 1](https://cloud.githubusercontent.com/assets/5178597/5852346/6bb3e4b8-a23d-11e4-9054-ba843336528a.png)
First letter of Lalitpur at the top, for example.

**Comment by Pujan789556** [comment]
Resolved
