### ISSUE TITLE
Center "found via search" brick kiln to the center of the viewport than center of the screen? 

### ISSUE THREAD

**Issue by share-hub** [Pujan789556/BrickKiln#16]
Right now, we get "found via search" brick kiln centered to the screen (as in fig a)..can we get this centered on the viewport (center of the visible map; as in fig b)....OR remove the keyboard after the user has selected his brick kiln and display it in the middle of the screen (as in fig c)? 

![screenshot_2015-01-22-13-41-59 1](https://cloud.githubusercontent.com/assets/5178597/5852506/04d438a8-a240-11e4-8194-6a7c23614584.png)
Fig a

![screenshot_2015-01-22-13-53-51 1](https://cloud.githubusercontent.com/assets/5178597/5852508/0e7891e2-a240-11e4-9269-a7735f817d39.png)
Fig b

![screenshot_2015-01-22-13-53-30 1](https://cloud.githubusercontent.com/assets/5178597/5852511/1918c95a-a240-11e4-9738-ff7412fffe95.png)
Fig c

**Comment by Pujan789556** [comment]
Resolved
