### ISSUE TITLE
Info box: question/answer on same line

### ISSUE THREAD

**Issue by prabhasp** [Pujan789556/BrickKiln#5]
In the info box: Pull in key/value pair into the same line, and bold the answer. Keep them the same color, that will make things look nicer. This will give you a lot of possibility to squish down the space on the info box.
The spacing between the various items should be reducible as well.

Overall thought here is to create less scrolling for the user, and possibly combining the tabs into a long info box that has section headlines.

**Comment by nirabpudasaini** [comment]
Also some answers have underscore in them like "one_chimmney", "force_draft". These should also be changed to be "One Chimmney", "Force Draft". etc. We should title case all the answers for consistency.
