### ISSUE TITLE
Info box: hide question/answer if no answer

### ISSUE THREAD

**Issue by prabhasp** [Pujan789556/BrickKiln#6]
In the info box: If value is NA or 999, I would suggest hiding the key / value pair, to save space as well as cognitive power for the user (why make them read all of the options if values are not there?). 
If it really _is_ necessary to show all of the possible questions that were asked, have some kind of "Show Unanswered Questions" link to show all the N/A and 999 data.

**Comment by Pujan789556** [comment]
Resolved
